name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v1
      with:
        ocaml-version: 5.1.1

    - name: Install dependencies
      run: opam install . --deps-only

    - name: Build Coq files
      run: make -f CoqMakefile

    - name: Build OCaml project with Dune
      run: dune build

    - name: Run tests with Dune
      run: dune test