name: CI

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-and-test:
    permissions:
      attestations: write
      contents: read
      id-token: write

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1

      # Cache OPAM packages
      - name: Cache OPAM packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.opam/
            ~/.opam-switch/
          key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - run: opam install base stdio dune coq -y
      - run: opam exec -- coq_makefile -f _CoqProject -o CoqMakefile
      - run: make -f CoqMakefile -j 7
      - run: opam exec -- dune build -j 7
      - run: opam exec -- dune test -f --verbose