name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1

      - name: Cache OPAM packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.opam/
            ~/.opam/*/switch/
          key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - name: Install dependencies
        run: opam install base stdio dune coq -y

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1

      - name: Cache Dune build artifacts
        uses: actions/cache@v3
        with:
          path: _build/default
          key: ${{ runner.os }}-dune-${{ hashFiles('**/*.ml', '**/*.mli', '**/*.v', '**/*.vo') }}
          restore-keys: |
            ${{ runner.os }}-dune-

      - name: Build Coq files
        run: eval $(opam env) && opam exec -- coq_makefile -f _CoqProject -o CoqMakefile && make -f CoqMakefile

      - name: Build OCaml project with Dune
        run: opam exec -- dune build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1

      - name: Run tests with Dune
        run: opam exec -- dune test -f --verbose